### ISSUE TITLE
Autogenerar QR

### ISSUE THREAD

**Issue by Jzarecta** [CryptosTabasco/Manatees#3]
Actualmente tenemos que subir el qr.jpg, pero creo que esto no es sostenible ya que se tiene QR para cada moneda y aunque la grafica es estatica es decir no se va a modificar con mas informacion, esta se puede auto-generar por un modulo de javascript (espero). 
Haciendo un pequeña busqueda encontre [este plugin de jquery](http://jeromeetienne.github.io/jquery-qrcode/).
Quizas se puede agregar para que se tenga en el modal.

**Comment by Biaku** [comment]
lo checo
